// <auto-generated />
using System;
using KlaraHome.Modules.Orders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cess")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cess");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cgst");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("igst");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Irn")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("irn");

                    b.Property<bool>("IsIntraState")
                        .HasColumnType("boolean")
                        .HasColumnName("is_intra_state");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PlaceOfSupplyStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("place_of_supply_state_code");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("qr_payload");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("series");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sgst");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_invoices_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_invoices_vendor_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_invoices_tenant_id_order_id");

                    b.HasIndex("TenantId", "SubOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_tenant_id_sub_order_id");

                    b.HasIndex("TenantId", "VendorId", "IssuedAt")
                        .HasDatabaseName("ix_invoices_tenant_id_vendor_id_issued_at");

                    b.HasIndex("TenantId", "VendorId", "FinancialYear", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_tenant_id_vendor_id_financial_year_invoice_number");

                    b.ToTable("invoices", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_invoices_amounts", "taxable_value >= 0 AND cgst >= 0 AND sgst >= 0 AND igst >= 0 AND cess >= 0 AND total >= 0");

                            t.HasCheckConstraint("ck_invoices_status", "status IN ('Issued', 'Cancelled')");

                            t.HasCheckConstraint("ck_invoices_tax_split", "(igst = 0) OR (cgst = 0 AND sgst = 0)");

                            t.HasCheckConstraint("ck_invoices_vendor", "vendor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_number_sequences");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_number_sequences_tenant_id");

                    b.HasIndex("TenantId", "Kind", "ScopeKey", "FinancialYear")
                        .IsUnique()
                        .HasDatabaseName("ix_number_sequences_tenant_id_kind_scope_key_financial_year");

                    b.ToTable("number_sequences", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_number_sequences_kind", "kind IN ('order', 'invoice')");

                            t.HasCheckConstraint("ck_number_sequences_next", "next_value >= 1");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPayable")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_payable");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("billing_address");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<Guid>("CheckoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.Property<decimal>("CodFee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cod_fee");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_snapshot");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_total");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("grand_total");

                    b.Property<decimal>("ItemsTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("items_total");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("PlaceOfSupplyStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_of_supply_state_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("placed_at");

                    b.Property<decimal>("RoundingAdjustment")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rounding_adjustment");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shipping_address");

                    b.Property<decimal>("ShippingTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax_total");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("WalletApplied")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("wallet_applied");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orders_tenant_id");

                    b.HasIndex("TenantId", "CartId")
                        .HasDatabaseName("ix_orders_tenant_id_cart_id");

                    b.HasIndex("TenantId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_order_number");

                    b.HasIndex("TenantId", "CustomerId", "PlacedAt")
                        .HasDatabaseName("ix_orders_tenant_id_customer_id_placed_at");

                    b.HasIndex("TenantId", "Status", "PlacedAt")
                        .HasDatabaseName("ix_orders_tenant_id_status_placed_at");

                    b.ToTable("orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_orders_channel", "channel IN ('web', 'app', 'admin')");

                            t.HasCheckConstraint("ck_orders_payment_method", "payment_method IN ('Prepaid', 'CashOnDelivery')");

                            t.HasCheckConstraint("ck_orders_payment_status", "payment_status IN ('Pending', 'Authorized', 'Paid', 'Failed', 'PartiallyRefunded', 'Refunded')");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('PendingPayment', 'InProgress', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("ck_orders_totals", "items_total >= 0 AND discount_total >= 0 AND shipping_total >= 0 AND tax_total >= 0 AND cod_fee >= 0 AND wallet_applied >= 0 AND grand_total >= 0 AND amount_payable >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("from_status");

                    b.Property<bool>("IsCustomerVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer_visible");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_order_events");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_events_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_events_tenant_id");

                    b.HasIndex("TenantId", "OrderId", "OccurredAt")
                        .HasDatabaseName("ix_order_events_tenant_id_order_id_occurred_at");

                    b.HasIndex("TenantId", "SubOrderId", "OccurredAt")
                        .HasDatabaseName("ix_order_events_tenant_id_sub_order_id_occurred_at");

                    b.ToTable("order_events", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_events_type", "type IN ('placed', 'status-changed', 'cancelled', 'invoiced', 'payment', 'note')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cess")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cess");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cgst");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("commission_amount");

                    b.Property<Guid?>("CommissionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_plan_id");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("GstRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("gst_rate");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("igst");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityCancelled")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_cancelled");

                    b.Property<int>("QuantityReturned")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_returned");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sgst");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitMrp")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_mrp");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_order_lines");

                    b.HasIndex("SubOrderId")
                        .HasDatabaseName("ix_order_lines_sub_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_lines_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_order_lines_vendor_id");

                    b.HasIndex("TenantId", "ListingId")
                        .HasDatabaseName("ix_order_lines_tenant_id_listing_id");

                    b.ToTable("order_lines", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_lines_money", "unit_mrp >= 0 AND unit_price >= 0 AND discount_amount >= 0 AND taxable_value >= 0 AND line_total >= 0 AND commission_amount >= 0");

                            t.HasCheckConstraint("ck_order_lines_quantities", "quantity >= 1 AND quantity_cancelled >= 0 AND quantity_returned >= 0 AND quantity_cancelled <= quantity AND quantity_returned <= quantity");

                            t.HasCheckConstraint("ck_order_lines_status", "status IN ('Active', 'PartiallyCancelled', 'Cancelled', 'PartiallyReturned', 'Returned')");

                            t.HasCheckConstraint("ck_order_lines_vendor", "vendor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.SubOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cancelled_by");

                    b.Property<string>("Carrier")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_total");

                    b.Property<DateTimeOffset?>("DispatchDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatch_due_at");

                    b.Property<int>("DispatchSlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_sla_hours");

                    b.Property<decimal>("ItemsTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("items_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PromisedMaxDays")
                        .HasColumnType("integer")
                        .HasColumnName("promised_max_days");

                    b.Property<int>("PromisedMinDays")
                        .HasColumnType("integer")
                        .HasColumnName("promised_min_days");

                    b.Property<DateTimeOffset?>("ReturnWindowEndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("return_window_ends_at");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("ShippingOptionCode")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("shipping_option_code");

                    b.Property<decimal>("ShippingTax")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_tax");

                    b.Property<decimal>("ShippingTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("SubOrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sub_order_number");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax_total");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor_code");

                    b.Property<string>("VendorGstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("vendor_gstin");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sub_orders");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_sub_orders_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sub_orders_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_sub_orders_vendor_id");

                    b.HasIndex("TenantId", "SubOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_orders_tenant_id_sub_order_number");

                    b.HasIndex("TenantId", "OrderId", "VendorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_orders_tenant_id_order_id_vendor_id");

                    b.HasIndex("TenantId", "Status", "DispatchDueAt")
                        .HasDatabaseName("ix_sub_orders_tenant_id_status_dispatch_due_at");

                    b.HasIndex("TenantId", "Status", "ReturnWindowEndsAt")
                        .HasDatabaseName("ix_sub_orders_tenant_id_status_return_window_ends_at");

                    b.HasIndex("TenantId", "VendorId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_sub_orders_tenant_id_vendor_id_status_created_at");

                    b.ToTable("sub_orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_sub_orders_cancelled_by", "cancelled_by IS NULL OR cancelled_by IN ('Customer', 'Vendor', 'Platform', 'System')");

                            t.HasCheckConstraint("ck_sub_orders_promise", "promised_min_days >= 0 AND promised_max_days >= promised_min_days AND dispatch_sla_hours >= 0");

                            t.HasCheckConstraint("ck_sub_orders_status", "status IN ('PendingPayment', 'PaymentFailed', 'Confirmed', 'Processing', 'Packed', 'Shipped', 'OutForDelivery', 'DeliveryFailed', 'RtoInitiated', 'RtoDelivered', 'Delivered', 'ReturnRequested', 'ReturnInProgress', 'Returned', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("ck_sub_orders_totals", "items_total >= 0 AND discount_total >= 0 AND shipping_total >= 0 AND tax_total >= 0 AND taxable_value >= 0 AND total >= 0");

                            t.HasCheckConstraint("ck_sub_orders_vendor", "vendor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.OrderEvent", b =>
                {
                    b.HasOne("KlaraHome.Modules.Orders.Domain.Order", null)
                        .WithMany("Events")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_events_orders_order_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.OrderLine", b =>
                {
                    b.HasOne("KlaraHome.Modules.Orders.Domain.SubOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_lines_sub_orders_sub_order_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.SubOrder", b =>
                {
                    b.HasOne("KlaraHome.Modules.Orders.Domain.Order", null)
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_orders_orders_order_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.Order", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("KlaraHome.Modules.Orders.Domain.SubOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
