// <auto-generated />
using System;
using KlaraHome.Modules.Returns.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Returns.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReturnsDbContext))]
    [Migration("20260906082233_InitialReturnsSchema")]
    partial class InitialReturnsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("returns")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cess")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cess");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cgst");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreditNoteNumber")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("credit_note_number");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("igst");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsIntraState")
                        .HasColumnType("boolean")
                        .HasColumnName("is_intra_state");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PlaceOfSupplyStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("place_of_supply_state_code");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_id");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("series");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sgst");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_credit_notes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credit_notes_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_credit_notes_vendor_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_credit_notes_tenant_id_order_id");

                    b.HasIndex("TenantId", "ReturnId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_notes_tenant_id_return_id");

                    b.HasIndex("TenantId", "VendorId", "IssuedAt")
                        .HasDatabaseName("ix_credit_notes_tenant_id_vendor_id_issued_at");

                    b.HasIndex("TenantId", "VendorId", "FinancialYear", "CreditNoteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_notes_tenant_id_vendor_id_financial_year_credit_note");

                    b.ToTable("credit_notes", "returns", t =>
                        {
                            t.HasCheckConstraint("ck_credit_notes_amounts", "taxable_value >= 0 AND cgst >= 0 AND sgst >= 0 AND igst >= 0 AND cess >= 0 AND total >= 0");

                            t.HasCheckConstraint("ck_credit_notes_tax_split", "(igst = 0) OR (cgst = 0 AND sgst = 0)");

                            t.HasCheckConstraint("ck_credit_notes_vendor", "vendor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("financial_year");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_number_sequences");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_number_sequences_tenant_id");

                    b.HasIndex("TenantId", "Kind", "ScopeKey", "FinancialYear")
                        .IsUnique()
                        .HasDatabaseName("ix_number_sequences_tenant_id_kind_scope_key_financial_year");

                    b.ToTable("number_sequences", "returns", t =>
                        {
                            t.HasCheckConstraint("ck_number_sequences_kind", "kind IN ('return', 'credit-note')");

                            t.HasCheckConstraint("ck_number_sequences_next", "next_value >= 1");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.ReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cess")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cess");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cgst");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("disposition");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("igst");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<string>("QcNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qc_note");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_accepted");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("refund_amount");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_id");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sgst");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_return_lines");

                    b.HasIndex("ReturnId")
                        .HasDatabaseName("ix_return_lines_return_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_return_lines_tenant_id");

                    b.HasIndex("TenantId", "OrderLineId")
                        .HasDatabaseName("ix_return_lines_tenant_id_order_line_id");

                    b.HasIndex("TenantId", "ReturnId", "OrderLineId")
                        .IsUnique()
                        .HasDatabaseName("ix_return_lines_tenant_id_return_id_order_line_id");

                    b.ToTable("return_lines", "returns", t =>
                        {
                            t.HasCheckConstraint("ck_return_lines_amounts", "taxable_value >= 0 AND cgst >= 0 AND sgst >= 0 AND igst >= 0 AND cess >= 0 AND refund_amount >= 0");

                            t.HasCheckConstraint("ck_return_lines_disposition", "disposition IN ('Pending', 'Restock', 'Scrap', 'Quarantine')");

                            t.HasCheckConstraint("ck_return_lines_quantities", "quantity > 0 AND quantity_accepted >= 0 AND quantity_accepted <= quantity");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.ReturnReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_replacement");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAutoApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_approved");

                    b.Property<bool>("IsPickupRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pickup_required");

                    b.Property<bool>("IsVendorFault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vendor_fault");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<bool>("RequiresEvidence")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_evidence");

                    b.Property<bool>("RequiresQc")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_qc");

                    b.Property<string>("ShippingPayer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shipping_payer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_return_reasons");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_return_reasons_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_return_reasons_tenant_id_code");

                    b.HasIndex("TenantId", "IsActive", "SortOrder")
                        .HasDatabaseName("ix_return_reasons_tenant_id_is_active_sort_order");

                    b.ToTable("return_reasons", "returns", t =>
                        {
                            t.HasCheckConstraint("ck_return_reasons_shipping_payer", "shipping_payer IN ('Platform', 'Vendor', 'Customer')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("approved_amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_note_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("EstimatedRefund")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estimated_refund");

                    b.Property<string>("EvidenceFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_file_ids");

                    b.Property<DateTimeOffset?>("InspectedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inspected_at");

                    b.Property<bool>("IsPickupRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pickup_required");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<DateTimeOffset?>("PickedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("picked_at");

                    b.Property<string>("PickupAwb")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pickup_awb");

                    b.Property<DateTimeOffset?>("PickupScheduledFor")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pickup_scheduled_for");

                    b.Property<Guid?>("PickupShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_shipment_id");

                    b.Property<Guid?>("QcBy")
                        .HasColumnType("uuid")
                        .HasColumnName("qc_by");

                    b.Property<string>("QcNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("qc_notes");

                    b.Property<bool?>("QcPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("qc_passed");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_note");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("refund_amount");

                    b.Property<Guid?>("RefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<string>("RefundMode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("refund_mode");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refunded_at");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejected_reason");

                    b.Property<Guid?>("ReplacementOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("replacement_order_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("return_number");

                    b.Property<decimal>("ReturnShippingFee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("return_shipping_fee");

                    b.Property<decimal>("ShippingRefundAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_refund_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<string>("SubOrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sub_order_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_returns");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_returns_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_returns_vendor_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_returns_tenant_id_order_id");

                    b.HasIndex("TenantId", "ReturnNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_returns_tenant_id_return_number");

                    b.HasIndex("TenantId", "SubOrderId")
                        .HasDatabaseName("ix_returns_tenant_id_sub_order_id");

                    b.HasIndex("TenantId", "CustomerId", "RequestedAt")
                        .HasDatabaseName("ix_returns_tenant_id_customer_id_requested_at");

                    b.HasIndex("TenantId", "Status", "RequestedAt")
                        .HasDatabaseName("ix_returns_tenant_id_status_requested_at");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_returns_tenant_id_vendor_id_status");

                    b.ToTable("returns", "returns", t =>
                        {
                            t.HasCheckConstraint("ck_returns_amounts", "estimated_refund >= 0 AND approved_amount >= 0 AND refund_amount >= 0 AND return_shipping_fee >= 0");

                            t.HasCheckConstraint("ck_returns_refund_mode", "refund_mode IS NULL OR refund_mode IN ('Original', 'Wallet')");

                            t.HasCheckConstraint("ck_returns_refund_settled", "(refund_amount = 0 AND refund_mode IS NULL) OR (refund_amount > 0 AND refund_mode IS NOT NULL)");

                            t.HasCheckConstraint("ck_returns_status", "status IN ('Requested', 'Approved', 'Rejected', 'PickupScheduled', 'Picked', 'InTransit', 'Received', 'QcPassed', 'QcFailed', 'Refunded', 'Replaced', 'Closed', 'Cancelled')");

                            t.HasCheckConstraint("ck_returns_type", "type IN ('Return', 'Replacement')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.ReturnLine", b =>
                {
                    b.HasOne("KlaraHome.Modules.Returns.Domain.ReturnRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_return_lines_returns_return_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Returns.Domain.ReturnRequest", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
