// <auto-generated />
using System;
using KlaraHome.Modules.Payments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Payments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.CodCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("CollectedAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("collected_amount");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("collected_at");

                    b.Property<Guid?>("CollectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("collected_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RemittanceReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("remittance_reference");

                    b.Property<decimal?>("RemittedAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("remitted_amount");

                    b.Property<DateTimeOffset?>("RemittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("remitted_at");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cod_collections");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cod_collections_tenant_id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_cod_collections_tenant_id_order_id");

                    b.HasIndex("TenantId", "SubOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_cod_collections_tenant_id_sub_order_id");

                    b.HasIndex("TenantId", "Status", "CollectedAt")
                        .HasDatabaseName("ix_cod_collections_tenant_id_status_collected_at");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_cod_collections_tenant_id_vendor_id_status");

                    b.ToTable("cod_collections", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_cod_collections_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_cod_collections_status", "status IN ('Pending', 'Collected', 'Remitted', 'Waived', 'WrittenOff')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.GatewayEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProcessError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("process_error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_valid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_gateway_events");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_gateway_events_tenant_id");

                    b.HasIndex("TenantId", "PaymentId")
                        .HasDatabaseName("ix_gateway_events_tenant_id_payment_id");

                    b.HasIndex("TenantId", "ReceivedAt")
                        .HasDatabaseName("ix_gateway_events_tenant_id_received_at");

                    b.HasIndex("TenantId", "Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_gateway_events_tenant_id_provider_provider_event_id");

                    b.HasIndex("TenantId", "Status", "NextAttemptAt")
                        .HasDatabaseName("ix_gateway_events_tenant_id_status_next_attempt_at");

                    b.ToTable("gateway_events", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_gateway_events_status", "status IN ('Pending', 'Processed', 'Ignored', 'Failed', 'DeadLettered')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.GatewaySettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fees");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<int>("MismatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("mismatch_count");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSettlementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_settlement_id");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Utr")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("utr");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_gateway_settlements");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_gateway_settlements_tenant_id");

                    b.HasIndex("TenantId", "SettledAt")
                        .HasDatabaseName("ix_gateway_settlements_tenant_id_settled_at");

                    b.HasIndex("TenantId", "Provider", "ProviderSettlementId")
                        .IsUnique()
                        .HasDatabaseName("ix_gateway_settlements_tenant_id_provider_provider_settlement_");

                    b.ToTable("gateway_settlements", "payments");
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.GatewaySettlementEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("debit");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("entry_type");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fee");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("match_status");

                    b.Property<string>("MismatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mismatch_reason");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderEntryId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_entry_id");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_payment_id");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_gateway_settlement_entries");

                    b.HasIndex("SettlementId")
                        .HasDatabaseName("ix_gateway_settlement_entries_settlement_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_gateway_settlement_entries_tenant_id");

                    b.HasIndex("TenantId", "PaymentId")
                        .HasDatabaseName("ix_gateway_settlement_entries_tenant_id_payment_id");

                    b.HasIndex("TenantId", "ProviderPaymentId")
                        .HasDatabaseName("ix_gateway_settlement_entries_tenant_id_provider_payment_id");

                    b.HasIndex("TenantId", "SettlementId", "MatchStatus")
                        .HasDatabaseName("ix_gateway_settlement_entries_tenant_id_settlement_id_match_st");

                    b.ToTable("gateway_settlement_entries", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_settlement_entries_match", "match_status IN ('Unmatched', 'Matched', 'Mismatched')");

                            t.HasCheckConstraint("ck_settlement_entries_type", "entry_type IN ('payment', 'refund', 'adjustment', 'transfer')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountCaptured")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_captured");

                    b.Property<decimal>("AmountRefunded")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_refunded");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("authorized_at");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_order_id");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reconciled_at");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payments_tenant_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_tenant_id_idempotency_key");

                    b.HasIndex("TenantId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_open_per_order")
                        .HasFilter("status IN ('Created', 'Authorized')");

                    b.HasIndex("TenantId", "OrderNumber")
                        .HasDatabaseName("ix_payments_tenant_id_order_number");

                    b.HasIndex("TenantId", "ProviderOrderId")
                        .HasDatabaseName("ix_payments_tenant_id_provider_order_id");

                    b.HasIndex("TenantId", "ProviderPaymentId")
                        .HasDatabaseName("ix_payments_tenant_id_provider_payment_id");

                    b.HasIndex("TenantId", "OrderId", "OpenedAt")
                        .HasDatabaseName("ix_payments_tenant_id_order_id_opened_at");

                    b.HasIndex("TenantId", "Status", "OpenedAt")
                        .HasDatabaseName("ix_payments_tenant_id_status_opened_at");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amounts", "amount >= 0 AND amount_captured >= 0 AND amount_refunded >= 0 AND amount_refunded <= amount_captured + 1");

                            t.HasCheckConstraint("ck_payments_method", "method IN ('Unknown', 'Upi', 'Card', 'NetBanking', 'Wallet', 'Emi', 'Cod')");

                            t.HasCheckConstraint("ck_payments_provider", "provider IN ('razorpay', 'internal_cod')");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Created', 'Authorized', 'Captured', 'PartiallyRefunded', 'Refunded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("attempted_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("method_detail");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_description");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_attempts");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_attempts_payment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payment_attempts_tenant_id");

                    b.HasIndex("TenantId", "ProviderPaymentId")
                        .HasDatabaseName("ix_payment_attempts_tenant_id_provider_payment_id");

                    b.HasIndex("TenantId", "PaymentId", "AttemptedAt")
                        .HasDatabaseName("ix_payment_attempts_tenant_id_payment_id_attempted_at");

                    b.ToTable("payment_attempts", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_attempts_method", "method IN ('Unknown', 'Upi', 'Card', 'NetBanking', 'Wallet', 'Emi', 'Cod')");

                            t.HasCheckConstraint("ck_payment_attempts_source", "source IN ('Checkout', 'Webhook', 'Reconciliation', 'Admin')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("initiated_at");

                    b.Property<Guid?>("InitiatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_refund_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejected_reason");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<Guid?>("ReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_id");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("speed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refunds");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_refunds_payment_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refunds_tenant_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_refunds_tenant_id_idempotency_key");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_refunds_tenant_id_order_id");

                    b.HasIndex("TenantId", "PaymentId")
                        .HasDatabaseName("ix_refunds_tenant_id_payment_id");

                    b.HasIndex("TenantId", "ProviderRefundId")
                        .HasDatabaseName("ix_refunds_tenant_id_provider_refund_id");

                    b.HasIndex("TenantId", "Status", "InitiatedAt")
                        .HasDatabaseName("ix_refunds_tenant_id_status_initiated_at");

                    b.ToTable("refunds", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_refunds_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_refunds_approver", "approved_by IS NULL OR initiated_by IS NULL OR approved_by <> initiated_by");

                            t.HasCheckConstraint("ck_refunds_speed", "speed IN ('Normal', 'Optimum')");

                            t.HasCheckConstraint("ck_refunds_status", "status IN ('Requested', 'Approved', 'Processing', 'Processed', 'Failed', 'Rejected')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.GatewaySettlementEntry", b =>
                {
                    b.HasOne("KlaraHome.Modules.Payments.Domain.GatewaySettlement", null)
                        .WithMany("Entries")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gateway_settlement_entries_gateway_settlements_settlement_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.PaymentAttempt", b =>
                {
                    b.HasOne("KlaraHome.Modules.Payments.Domain.Payment", null)
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_attempts_payments_payment_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.Refund", b =>
                {
                    b.HasOne("KlaraHome.Modules.Payments.Domain.Payment", null)
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refunds_payments_payment_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.GatewaySettlement", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("KlaraHome.Modules.Payments.Domain.Payment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
