// <auto-generated />
using System;
using System.Collections.Generic;
using KlaraHome.Modules.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace KlaraHome.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sku_seq", "catalog");

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.AttributeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("SwatchHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("swatch_hex")
                        .IsFixedLength(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attribute_options");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attribute_options_tenant_id");

                    b.HasIndex("TenantId", "AttributeId", "Position")
                        .HasDatabaseName("ix_attribute_options_tenant_id_attribute_id_position");

                    b.HasIndex("TenantId", "AttributeId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_attribute_options_tenant_id_attribute_id_value");

                    b.ToTable("attribute_options", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.AttributeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attribute_sets");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attribute_sets_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_attribute_sets_tenant_id_code");

                    b.ToTable("attribute_sets", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.AttributeSetMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("AttributeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_set_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attribute_set_members");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attribute_set_members_tenant_id");

                    b.HasIndex("TenantId", "AttributeSetId", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("ix_attribute_set_members_tenant_id_attribute_set_id_attribute_");

                    b.HasIndex("TenantId", "AttributeSetId", "Position")
                        .HasDatabaseName("ix_attribute_set_members_tenant_id_attribute_set_id_position");

                    b.ToTable("attribute_set_members", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_brands_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_brands_tenant_id_name");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_brands_tenant_id_slug");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.CatalogJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<string>("ResultKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("result_key");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_key");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SucceededRows")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_rows");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_catalog_jobs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_jobs_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_catalog_jobs_vendor_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_catalog_jobs_status_created_at")
                        .HasFilter("status = 'Queued'");

                    b.HasIndex("TenantId", "VendorId", "CreatedAt")
                        .HasDatabaseName("ix_catalog_jobs_tenant_id_vendor_id_created_at");

                    b.ToTable("catalog_jobs", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_jobs_counts", "total_rows >= 0 AND processed_rows >= 0 AND succeeded_rows >= 0 AND failed_rows >= 0");

                            t.HasCheckConstraint("ck_catalog_jobs_kind", "kind IN ('ProductImport', 'ProductExport')");

                            t.HasCheckConstraint("ck_catalog_jobs_status", "status IN ('Queued', 'Running', 'Succeeded', 'PartiallySucceeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.CatalogMediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_media_assets_tenant_id");

                    b.HasIndex("TenantId", "ProductId", "Position")
                        .HasDatabaseName("ix_media_assets_tenant_id_product_id_position");

                    b.HasIndex("TenantId", "VariantId", "Position")
                        .HasDatabaseName("ix_media_assets_tenant_id_variant_id_position");

                    b.HasIndex("TenantId", "ProductId", "VariantId", "FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_assets_tenant_id_product_id_variant_id_file_id");

                    b.ToTable("media_assets", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_kind", "kind IN ('Image', 'Video', 'Document')");

                            t.HasCheckConstraint("ck_media_assets_owner", "product_id IS NOT NULL OR variant_id IS NOT NULL");

                            t.HasCheckConstraint("ck_media_assets_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttributeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_set_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_file_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("path");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_categories_tenant_id");

                    b.HasIndex("TenantId", "Path")
                        .HasDatabaseName("ix_categories_tenant_id_path");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_tenant_id_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "ParentId", "Position")
                        .HasDatabaseName("ix_categories_tenant_id_parent_id_position");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_categories_level", "level >= 0 AND level < 6");

                            t.HasCheckConstraint("ck_categories_parent", "(level = 0 AND parent_id IS NULL) OR (level > 0 AND parent_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_categories_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("HandlingTimeHours")
                        .HasColumnType("integer")
                        .HasColumnName("handling_time_hours");

                    b.Property<bool>("IsCodAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cod_allowed");

                    b.Property<int?>("MaxOrderQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_order_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorSku")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor_sku");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Mrp", "KlaraHome.Modules.Catalog.Domain.Listing.Mrp#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("mrp_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("mrp_currency_code");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SellingPrice", "KlaraHome.Modules.Catalog.Domain.Listing.SellingPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("selling_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("selling_price_currency_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_listings_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_listings_vendor_id");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_listings_tenant_id_product_id");

                    b.HasIndex("TenantId", "VariantId", "Status")
                        .HasDatabaseName("ix_listings_tenant_id_variant_id_status");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_listings_tenant_id_vendor_id_status");

                    b.HasIndex("TenantId", "VendorId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_listings_tenant_id_vendor_id_variant_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("listings", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_listings_handling_time", "handling_time_hours > 0 AND handling_time_hours <= 168");

                            t.HasCheckConstraint("ck_listings_max_order_quantity", "max_order_quantity IS NULL OR max_order_quantity > 0");

                            t.HasCheckConstraint("ck_listings_price_below_mrp", "selling_price_amount <= mrp_amount");

                            t.HasCheckConstraint("ck_listings_prices_positive", "mrp_amount >= 0 AND selling_price_amount >= 0");

                            t.HasCheckConstraint("ck_listings_status", "status IN ('Draft', 'Active', 'Inactive', 'Archived')");

                            t.HasCheckConstraint("ck_listings_vendor_present", "vendor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_of_origin")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GstRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("gst_rate");

                    b.Property<string>("HsnCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("hsn_code");

                    b.Property<bool>("IsReturnable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_returnable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("RatingAverage")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int?>("ReturnWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("return_window_days");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(short_description, ''))", true);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("Warranty")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("warranty");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_products_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_products_vendor_id");

                    b.HasIndex("TenantId", "BrandId")
                        .HasDatabaseName("ix_products_tenant_id_brand_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "CategoryId", "Status")
                        .HasDatabaseName("ix_products_tenant_id_category_id_status");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_products_tenant_id_vendor_id_status");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_products_country_of_origin", "country_of_origin IS NULL OR char_length(country_of_origin) = 2");

                            t.HasCheckConstraint("ck_products_gst_rate", "gst_rate >= 0 AND gst_rate <= 100");

                            t.HasCheckConstraint("ck_products_hsn", "hsn_code IS NULL OR char_length(hsn_code) IN (4, 6, 8)");

                            t.HasCheckConstraint("ck_products_rating", "rating_average IS NULL OR (rating_average >= 0 AND rating_average <= 5)");

                            t.HasCheckConstraint("ck_products_rating_count", "rating_count >= 0");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Draft', 'PendingApproval', 'Active', 'Inactive', 'Archived')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("data_type");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_filterable");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsVariantDefining")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variant_defining");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attributes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_attributes_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_attributes_tenant_id_code");

                    b.HasIndex("TenantId", "IsFilterable", "Position")
                        .HasDatabaseName("ix_attributes_tenant_id_is_filterable_position");

                    b.ToTable("attributes", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_attributes_data_type", "data_type IN ('Text', 'Number', 'Boolean', 'Select', 'MultiSelect', 'Date')");

                            t.HasCheckConstraint("ck_attributes_variant_defining", "is_variant_defining = false OR data_type IN ('Select', 'MultiSelect')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("boolean")
                        .HasColumnName("value_boolean");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value_number");

                    b.Property<Guid?>("ValueOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("value_option_id");

                    b.Property<string>("ValueText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value_text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_product_attribute_values");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_attribute_values_tenant_id");

                    b.HasIndex("TenantId", "AttributeId", "ValueOptionId")
                        .HasDatabaseName("ix_product_attribute_values_tenant_id_attribute_id_value_optio");

                    b.HasIndex("TenantId", "ProductId", "AttributeId", "ValueOptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_attribute_values_tenant_id_product_id_attribute_id_");

                    b.ToTable("product_attribute_values", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.ProductModeration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_product_moderations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_moderations_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_product_moderations_vendor_id");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_moderations_tenant_id_product_id")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TenantId", "ProductId", "SubmittedAt")
                        .HasDatabaseName("ix_product_moderations_tenant_id_product_id_submitted_at");

                    b.HasIndex("TenantId", "Status", "SubmittedAt")
                        .HasDatabaseName("ix_product_moderations_tenant_id_status_submitted_at");

                    b.ToTable("product_moderations", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_moderations_rejection", "status <> 'Rejected' OR notes IS NOT NULL");

                            t.HasCheckConstraint("ck_product_moderations_reviewed", "(status = 'Pending') = (reviewed_at IS NULL)");

                            t.HasCheckConstraint("ck_product_moderations_status", "status IN ('Pending', 'Approved', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("attribute_hash")
                        .IsFixedLength();

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<int>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<string>("NameSuffix")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_suffix");

                    b.Property<string>("NetQuantity")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("net_quantity");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_days");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("WeightGrams")
                        .HasColumnType("integer")
                        .HasColumnName("weight_grams");

                    b.Property<int>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Mrp", "KlaraHome.Modules.Catalog.Domain.Variant.Mrp#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("mrp_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("mrp_currency_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_variants");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_variants_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_variants_tenant_id");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_variants_tenant_id_sku")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "ProductId", "AttributeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_variants_tenant_id_product_id_attribute_hash")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "ProductId", "Position")
                        .HasDatabaseName("ix_variants_tenant_id_product_id_position");

                    b.ToTable("variants", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_variants_dimensions", "weight_grams >= 0 AND length_mm >= 0 AND width_mm >= 0 AND height_mm >= 0");

                            t.HasCheckConstraint("ck_variants_mrp", "mrp_amount >= 0");

                            t.HasCheckConstraint("ck_variants_shelf_life", "shelf_life_days IS NULL OR shelf_life_days > 0");

                            t.HasCheckConstraint("ck_variants_status", "status IN ('Draft', 'Active', 'Inactive', 'Archived')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.VariantAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_variant_attribute_values");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_variant_attribute_values_tenant_id");

                    b.HasIndex("TenantId", "AttributeId", "OptionId")
                        .HasDatabaseName("ix_variant_attribute_values_tenant_id_attribute_id_option_id");

                    b.HasIndex("TenantId", "VariantId", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("ix_variant_attribute_values_tenant_id_variant_id_attribute_id");

                    b.ToTable("variant_attribute_values", "catalog");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Brand", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("BrandId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoIndex");

                            b1.HasKey("BrandId");

                            b1.ToTable("brands", "catalog");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BrandId")
                                .HasConstraintName("fk_brands_brands_id");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.CatalogJob", b =>
                {
                    b.OwnsMany("KlaraHome.Modules.Catalog.Domain.ImportRowError", "Errors", b1 =>
                        {
                            b1.Property<Guid>("CatalogJobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Column");

                            b1.Property<string>("Message")
                                .IsRequired();

                            b1.Property<int>("RowNumber");

                            b1.Property<string>("Sku");

                            b1.HasKey("CatalogJobId", "__synthesizedOrdinal");

                            b1.ToTable("catalog_jobs", "catalog");

                            b1
                                .ToJson("errors")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CatalogJobId")
                                .HasConstraintName("fk_catalog_jobs_catalog_jobs_catalog_job_id");
                        });

                    b.Navigation("Errors");
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Category", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CategoryId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoIndex");

                            b1.HasKey("CategoryId")
                                .HasName("pk_categories");

                            b1.ToTable("categories", "catalog");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_category_id");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("KlaraHome.Modules.Catalog.Domain.Product", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.PartyDetails", "Importer", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<string>("Address")
                                .IsRequired();

                            b1.Property<string>("Contact");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1
                                .ToJson("importer")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.PartyDetails", "Manufacturer", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<string>("Address")
                                .IsRequired();

                            b1.Property<string>("Contact");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("ProductId")
                                .HasName("pk_products");

                            b1.ToTable("products", "catalog");

                            b1
                                .ToJson("manufacturer")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_product_id");
                        });

                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.PartyDetails", "Packer", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<string>("Address")
                                .IsRequired();

                            b1.Property<string>("Contact");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1
                                .ToJson("packer")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("KlaraHome.Modules.Catalog.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoIndex");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsMany("KlaraHome.Modules.Catalog.Domain.Specification", "Specifications", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Group");

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ProductId", "__synthesizedOrdinal");

                            b1.ToTable("products", "catalog");

                            b1
                                .ToJson("specifications")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_product_id");
                        });

                    b.Navigation("Importer")
                        .IsRequired();

                    b.Navigation("Manufacturer")
                        .IsRequired();

                    b.Navigation("Packer")
                        .IsRequired();

                    b.Navigation("Seo")
                        .IsRequired();

                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
