// <auto-generated />
using System;
using System.Collections.Generic;
using KlaraHome.Modules.Search.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace KlaraHome.Modules.Search.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20260906101931_SearchQueryPartitions")]
    partial class SearchQueryPartitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("search")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Search.Domain.ProductSearchDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeMeta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attribute_meta");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("BrandName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("brand_name");

                    b.Property<string>("BrandSlug")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("brand_slug");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.PrimitiveCollection<List<Guid>>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("category_ids");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("category_name");

                    b.Property<string>("CategoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("category_path");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("category_slug");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsCodAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cod_allowed");

                    b.Property<bool>("IsReturnable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_returnable");

                    b.Property<string>("Keywords")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("keywords");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("Mrp")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("mrp");

                    b.Property<int>("OfferCount")
                        .HasColumnType("integer")
                        .HasColumnName("offer_count");

                    b.Property<decimal>("PopularityScore")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("popularity_score");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<Guid?>("PrimaryImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_image_file_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSlug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("product_slug");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_available");

                    b.Property<decimal?>("RatingAverage")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(product_name, '')), 'A') ||\r\nsetweight(to_tsvector('english', coalesce(brand_name, '') || ' ' || coalesce(variant_name, '') || ' ' || coalesce(sku, '')), 'B') ||\r\nsetweight(to_tsvector('english', coalesce(category_name, '')), 'C') ||\r\nsetweight(to_tsvector('english', coalesce(keywords, '')), 'D')", true);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UnitsSold")
                        .HasColumnType("bigint")
                        .HasColumnName("units_sold");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("variant_name");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("vendor_name");

                    b.Property<decimal?>("VendorRating")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("vendor_rating");

                    b.Property<string>("VendorSlug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("vendor_slug");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_product_search_projection");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_product_search_projection_attributes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");

                    b.HasIndex("CategoryIds")
                        .HasDatabaseName("ix_product_search_projection_category_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryIds"), "gin");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("ix_product_search_projection_product_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProductName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProductName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_product_search_projection_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_search_projection_tenant_id");

                    b.HasIndex("TenantId", "BrandId")
                        .HasDatabaseName("ix_product_search_projection_tenant_id_brand_id");

                    b.HasIndex("TenantId", "IndexedAt")
                        .HasDatabaseName("ix_product_search_projection_stale")
                        .HasFilter("is_active = true");

                    b.HasIndex("TenantId", "ListingId")
                        .HasDatabaseName("ix_product_search_projection_tenant_id_listing_id");

                    b.HasIndex("TenantId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_search_projection_tenant_id_variant_id");

                    b.HasIndex("TenantId", "VendorId")
                        .HasDatabaseName("ix_product_search_projection_tenant_id_vendor_id");

                    b.HasIndex("TenantId", "CategoryPath", "Price")
                        .HasDatabaseName("ix_product_search_projection_tenant_id_category_path_price");

                    b.HasIndex("TenantId", "IsActive", "PopularityScore")
                        .HasDatabaseName("ix_product_search_projection_tenant_id_is_active_popularity_sc");

                    b.ToTable("product_search_projection", "search", t =>
                        {
                            t.HasCheckConstraint("ck_product_search_projection_amounts", "mrp >= 0 AND price >= 0 AND mrp >= price");

                            t.HasCheckConstraint("ck_product_search_projection_counts", "rating_count >= 0 AND offer_count >= 0 AND quantity_available >= 0 AND units_sold >= 0");

                            t.HasCheckConstraint("ck_product_search_projection_discount", "discount_percent >= 0 AND discount_percent <= 100");

                            t.HasCheckConstraint("ck_product_search_projection_rating", "(rating_average IS NULL OR (rating_average >= 0 AND rating_average <= 5)) AND (vendor_rating IS NULL OR (vendor_rating >= 0 AND vendor_rating <= 5))");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Search.Domain.SearchQueryLogEntry", b =>
                {
                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClickedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("clicked_at");

                    b.Property<int?>("ClickedPosition")
                        .HasColumnType("integer")
                        .HasColumnName("clicked_position");

                    b.Property<Guid?>("ClickedVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("clicked_variant_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Filters")
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<string>("NormalisedQuery")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalised_query");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("query_text");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("CreatedAt", "Id")
                        .HasName("pk_search_queries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_queries_tenant_id");

                    b.ToTable("search_queries", "search", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Search.Domain.SearchStopWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("word");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_search_stop_words");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_stop_words_tenant_id");

                    b.HasIndex("TenantId", "Word")
                        .IsUnique()
                        .HasDatabaseName("ix_search_stop_words_tenant_id_word");

                    b.ToTable("search_stop_words", "search");
                });

            modelBuilder.Entity("KlaraHome.Modules.Search.Domain.SearchSynonym", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<List<string>>("Expansions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("expansions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bidirectional");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("term");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_search_synonyms");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_search_synonyms_tenant_id");

                    b.HasIndex("TenantId", "Term")
                        .IsUnique()
                        .HasDatabaseName("ix_search_synonyms_tenant_id_term");

                    b.ToTable("search_synonyms", "search", t =>
                        {
                            t.HasCheckConstraint("ck_search_synonyms_expansions", "cardinality(expansions) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
