// <auto-generated />
using System;
using KlaraHome.Modules.Carts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Carts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CartsDbContext))]
    [Migration("20260906032558_InitialCartsSchema")]
    partial class InitialCartsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("carts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("abandoned_at");

                    b.Property<string>("AnonymousTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anonymous_token_hash");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("converted_at");

                    b.Property<Guid?>("ConvertedOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_order_id");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTimeOffset?>("LastReminderAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_reminder_at");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasColumnName("line_count");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_carts_tenant_id");

                    b.HasIndex("TenantId", "AnonymousTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_carts_tenant_id_anonymous_token_hash")
                        .HasFilter("anonymous_token_hash IS NOT NULL");

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_carts_tenant_id_customer_id")
                        .HasFilter("customer_id IS NOT NULL AND status = 'Active'");

                    b.HasIndex("TenantId", "Status", "AbandonedAt")
                        .HasDatabaseName("ix_carts_tenant_id_status_abandoned_at");

                    b.HasIndex("TenantId", "Status", "LastActivityAt")
                        .HasDatabaseName("ix_carts_tenant_id_status_last_activity_at");

                    b.ToTable("carts", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_carts_line_count", "line_count >= 0");

                            t.HasCheckConstraint("ck_carts_owner", "customer_id IS NOT NULL OR anonymous_token_hash IS NOT NULL");

                            t.HasCheckConstraint("ck_carts_reminder_count", "reminder_count >= 0");

                            t.HasCheckConstraint("ck_carts_status", "status IN ('Active', 'Converted', 'Abandoned', 'Expired')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CartLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateTimeOffset>("PricedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("priced_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("SavedForLater")
                        .HasColumnType("boolean")
                        .HasColumnName("saved_for_later");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPriceAtAdd")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price_at_add");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cart_lines");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_lines_cart_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cart_lines_tenant_id");

                    b.HasIndex("TenantId", "VendorId")
                        .HasDatabaseName("ix_cart_lines_tenant_id_vendor_id");

                    b.HasIndex("TenantId", "CartId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_cart_lines_tenant_id_cart_id_listing_id");

                    b.ToTable("cart_lines", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_cart_lines_quantity", "quantity >= 1");

                            t.HasCheckConstraint("ck_cart_lines_unit_price", "unit_price_at_add >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_checkout_placements");

                    b.HasIndex("CheckoutSessionId")
                        .HasDatabaseName("ix_checkout_placements_checkout_session_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_checkout_placements_tenant_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_placements_tenant_id_idempotency_key");

                    b.ToTable("checkout_placements", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_checkout_placements_status", "status IN ('InProgress', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("jsonb")
                        .HasColumnName("billing_address");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("grand_total");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("gstin");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("PlaceOfSupplyStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_of_supply_state_id");

                    b.Property<DateTimeOffset?>("PlacedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("placed_at");

                    b.Property<string>("QuoteSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("quote_snapshot");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("jsonb")
                        .HasColumnName("shipping_address");

                    b.Property<decimal>("ShippingTotal")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_checkout_sessions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_checkout_sessions_tenant_id");

                    b.HasIndex("TenantId", "CartId")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_sessions_tenant_id_cart_id")
                        .HasFilter("status IN ('Draft', 'AddressSet', 'ShippingSet', 'PaymentSet', 'Placing')");

                    b.HasIndex("TenantId", "CustomerId", "Status")
                        .HasDatabaseName("ix_checkout_sessions_tenant_id_customer_id_status");

                    b.HasIndex("TenantId", "Status", "ExpiresAt")
                        .HasDatabaseName("ix_checkout_sessions_tenant_id_status_expires_at");

                    b.ToTable("checkout_sessions", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_checkout_sessions_payment", "payment_method IN ('Prepaid', 'CashOnDelivery')");

                            t.HasCheckConstraint("ck_checkout_sessions_status", "status IN ('Draft', 'AddressSet', 'ShippingSet', 'PaymentSet', 'Placing', 'Placed', 'Abandoned', 'Expired')");

                            t.HasCheckConstraint("ck_checkout_sessions_totals", "shipping_total >= 0 AND grand_total >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutShipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Carrier")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("carrier");

                    b.Property<Guid>("CheckoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkout_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DispatchSlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_sla_hours");

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("option_code");

                    b.Property<int>("PromisedMaxDays")
                        .HasColumnType("integer")
                        .HasColumnName("promised_max_days");

                    b.Property<int>("PromisedMinDays")
                        .HasColumnType("integer")
                        .HasColumnName("promised_min_days");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("service_name");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tax_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_checkout_shipments");

                    b.HasIndex("CheckoutSessionId")
                        .HasDatabaseName("ix_checkout_shipments_checkout_session_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_checkout_shipments_tenant_id");

                    b.HasIndex("TenantId", "CheckoutSessionId", "VendorId")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_shipments_tenant_id_checkout_session_id_vendor_id");

                    b.ToTable("checkout_shipments", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_checkout_shipments_amount", "amount >= 0 AND tax_amount >= 0");

                            t.HasCheckConstraint("ck_checkout_shipments_promise", "promised_min_days >= 0 AND promised_max_days >= promised_min_days");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CartLine", b =>
                {
                    b.HasOne("KlaraHome.Modules.Carts.Domain.Cart", null)
                        .WithMany("Lines")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_lines_carts_cart_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutPlacement", b =>
                {
                    b.HasOne("KlaraHome.Modules.Carts.Domain.CheckoutSession", null)
                        .WithMany("Placements")
                        .HasForeignKey("CheckoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkout_placements_checkout_sessions_checkout_session_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutShipment", b =>
                {
                    b.HasOne("KlaraHome.Modules.Carts.Domain.CheckoutSession", null)
                        .WithMany("Shipments")
                        .HasForeignKey("CheckoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkout_shipments_checkout_sessions_checkout_session_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.Cart", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("KlaraHome.Modules.Carts.Domain.CheckoutSession", b =>
                {
                    b.Navigation("Placements");

                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
