// <auto-generated />
using System;
using KlaraHome.Modules.Settlements.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Settlements.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SettlementsDbContext))]
    partial class SettlementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("settlements")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.CommissionInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cgst");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("commission");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<decimal>("GstRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("gst_rate");

                    b.Property<decimal>("Igst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("igst");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<decimal>("PaymentFee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("payment_fee");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<string>("PlaceOfSupplyStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("place_of_supply_state_code");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("platform_fee");

                    b.Property<string>("RecipientGstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("recipient_gstin");

                    b.Property<Guid>("SettlementCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_cycle_id");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sgst");

                    b.Property<string>("SupplierGstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("supplier_gstin");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_commission_invoices");

                    b.HasIndex("SettlementCycleId")
                        .IsUnique()
                        .HasDatabaseName("ix_commission_invoices_settlement_cycle_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_commission_invoices_tenant_id");

                    b.HasIndex("TenantId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_commission_invoices_tenant_id_invoice_number");

                    b.HasIndex("TenantId", "VendorId", "IssuedAt")
                        .HasDatabaseName("ix_commission_invoices_tenant_id_vendor_id_issued_at");

                    b.ToTable("commission_invoices", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_commission_invoices_money", "commission >= 0 AND platform_fee >= 0 AND payment_fee >= 0 AND taxable_value >= 0 AND cgst >= 0 AND sgst >= 0 AND igst >= 0 AND total >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<Guid?>("PayoutBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_batch_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("SettlementCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_cycle_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_key");

                    b.Property<Guid?>("SubOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_order_id");

                    b.Property<decimal>("TaxableValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ledger_entries_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_ledger_entries_vendor_id");

                    b.HasIndex("TenantId", "PayoutBatchId")
                        .HasDatabaseName("ix_ledger_entries_tenant_id_payout_batch_id");

                    b.HasIndex("TenantId", "SettlementCycleId")
                        .HasDatabaseName("ix_ledger_entries_tenant_id_settlement_cycle_id");

                    b.HasIndex("TenantId", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_tenant_id_source_key");

                    b.HasIndex("TenantId", "SubOrderId")
                        .HasDatabaseName("ix_ledger_entries_tenant_id_sub_order_id");

                    b.HasIndex("TenantId", "VendorId", "OccurredAt")
                        .HasDatabaseName("ix_ledger_entries_unsettled")
                        .HasFilter("settlement_cycle_id IS NULL");

                    b.ToTable("ledger_entries", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amounts", "amount >= 0 AND taxable_value >= 0");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "direction IN ('Credit', 'Debit')");

                            t.HasCheckConstraint("ck_ledger_entries_reference", "reference_type IN ('sub-order', 'credit-note', 'cycle', 'payout', 'manual')");

                            t.HasCheckConstraint("ck_ledger_entries_type", "entry_type IN ('sale', 'commission', 'platform_tax', 'platform_fee', 'payment_fee', 'shipping_fee', 'refund', 'refund_commission_reversal', 'tcs', 'tds', 'adjustment', 'payout')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_number_sequences");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_number_sequences_tenant_id");

                    b.HasIndex("TenantId", "Kind", "ScopeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_number_sequences_tenant_id_kind_scope_key");

                    b.ToTable("number_sequences", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_number_sequences_kind", "kind IN ('payout', 'commission-invoice')");

                            t.HasCheckConstraint("ck_number_sequences_next", "next_value >= 1");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.PayoutBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancelled_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_batch_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("VendorCount")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_count");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_payout_batches");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payout_batches_tenant_id");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_payout_batches_tenant_id_reference");

                    b.HasIndex("TenantId", "Status", "RequestedAt")
                        .HasDatabaseName("ix_payout_batches_tenant_id_status_requested_at");

                    b.ToTable("payout_batches", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_payout_batches_amounts", "total_amount >= 0 AND vendor_count >= 0");

                            t.HasCheckConstraint("ck_payout_batches_approval", "(approved_by IS NULL AND approved_at IS NULL) OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_payout_batches_self_approval", "approved_by IS NULL OR requested_by IS NULL OR approved_by <> requested_by");

                            t.HasCheckConstraint("ck_payout_batches_status", "status IN ('Draft', 'Approved', 'Processing', 'Completed', 'PartiallyFailed', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.PayoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<string>("DestinationAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("DestinationLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("destination_last4");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("PayoutBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_batch_id");

                    b.Property<string>("ProviderPayoutId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_payout_id");

                    b.Property<string>("ProviderStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_status");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("settled_at");

                    b.Property<Guid?>("SettlementCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_cycle_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Utr")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("utr");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor_code");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_payout_items");

                    b.HasIndex("PayoutBatchId")
                        .HasDatabaseName("ix_payout_items_payout_batch_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payout_items_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_payout_items_vendor_id");

                    b.HasIndex("TenantId", "SettlementCycleId")
                        .HasDatabaseName("ix_payout_items_tenant_id_settlement_cycle_id");

                    b.HasIndex("TenantId", "PayoutBatchId", "VendorId")
                        .IsUnique()
                        .HasDatabaseName("ix_payout_items_tenant_id_payout_batch_id_vendor_id");

                    b.HasIndex("TenantId", "Status", "SentAt")
                        .HasDatabaseName("ix_payout_items_tenant_id_status_sent_at");

                    b.HasIndex("TenantId", "VendorId", "CreatedAt")
                        .HasDatabaseName("ix_payout_items_tenant_id_vendor_id_created_at");

                    b.ToTable("payout_items", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_payout_items_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_payout_items_completed", "status <> 'Completed' OR provider_payout_id IS NOT NULL");

                            t.HasCheckConstraint("ck_payout_items_status", "status IN ('Pending', 'Processing', 'Completed', 'Failed', 'Skipped')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.SettlementCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency_code");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gross_sales");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("net_payable");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("opening_balance");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PayoutBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_batch_id");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxableRefunds")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_refunds");

                    b.Property<decimal>("TaxableSales")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxable_sales");

                    b.Property<decimal>("Tcs")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tcs");

                    b.Property<decimal>("Tds")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tds");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAdjustments")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_adjustments");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_commission");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_fees");

                    b.Property<decimal>("TotalPayouts")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_payouts");

                    b.Property<decimal>("TotalRefunds")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_refunds");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_settlement_cycles");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_settlement_cycles_tenant_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_settlement_cycles_vendor_id");

                    b.HasIndex("TenantId", "PayoutBatchId")
                        .HasDatabaseName("ix_settlement_cycles_tenant_id_payout_batch_id");

                    b.HasIndex("TenantId", "Status", "PeriodEnd")
                        .HasDatabaseName("ix_settlement_cycles_tenant_id_status_period_end");

                    b.HasIndex("TenantId", "VendorId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_settlement_cycles_tenant_id_vendor_id_period_start");

                    b.ToTable("settlement_cycles", "settlements", t =>
                        {
                            t.HasCheckConstraint("ck_settlement_cycles_amounts", "gross_sales >= 0 AND taxable_sales >= 0 AND total_commission >= 0 AND total_fees >= 0 AND total_refunds >= 0 AND taxable_refunds >= 0 AND tcs >= 0 AND tds >= 0");

                            t.HasCheckConstraint("ck_settlement_cycles_closed", "(status = 'Open' AND closed_at IS NULL) OR (status <> 'Open' AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_settlement_cycles_period", "period_end > period_start");

                            t.HasCheckConstraint("ck_settlement_cycles_status", "status IN ('Open', 'Closed', 'Paid')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.PayoutItem", b =>
                {
                    b.HasOne("KlaraHome.Modules.Settlements.Domain.PayoutBatch", null)
                        .WithMany("Items")
                        .HasForeignKey("PayoutBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payout_items_payout_batches_payout_batch_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Settlements.Domain.PayoutBatch", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
