// <auto-generated />
using System;
using KlaraHome.Modules.Reviews.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Reviews.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20260906124720_InitialReviewsSchema")]
    partial class InitialReviewsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviews")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.AbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_abuse_reports");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_abuse_reports_tenant_id");

                    b.HasIndex("Target", "TargetId", "Status")
                        .HasDatabaseName("ix_abuse_reports_target_type_target_id_status");

                    b.HasIndex("TenantId", "Status", "Reason", "CreatedAt")
                        .HasDatabaseName("ix_abuse_reports_tenant_id_status_reason_created_at");

                    b.HasIndex("TenantId", "Target", "TargetId", "ReporterId")
                        .IsUnique()
                        .HasDatabaseName("ux_abuse_reports_open")
                        .HasFilter("status = 'Open' AND reporter_id IS NOT NULL");

                    b.ToTable("abuse_reports", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_abuse_reports_reason", "reason IN ('Spam', 'Offensive', 'Irrelevant', 'Misleading', 'PersonalData', 'Illegal', 'Other')");

                            t.HasCheckConstraint("ck_abuse_reports_status", "status IN ('Open', 'Upheld', 'Dismissed')");

                            t.HasCheckConstraint("ck_abuse_reports_target", "target_type IN ('Review', 'Question', 'Answer')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_type");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("moderated_at");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("moderated_by");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("report_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_answers_tenant_id");

                    b.HasIndex("QuestionId", "CreatedAt")
                        .HasDatabaseName("ix_answers_question_id_created_at");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_answers_tenant_id_status_created_at");

                    b.ToTable("answers", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_answers_author", "author_type IN ('Customer', 'Vendor', 'Store')");

                            t.HasCheckConstraint("ck_answers_status", "status IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("ck_answers_vendor", "(author_type = 'Vendor' AND vendor_id IS NOT NULL) OR (author_type <> 'Vendor' AND vendor_id IS NULL)");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.ProductRatingSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Average")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("average");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("FiveStar")
                        .HasColumnType("integer")
                        .HasColumnName("five_star");

                    b.Property<int>("FourStar")
                        .HasColumnType("integer")
                        .HasColumnName("four_star");

                    b.Property<int>("OneStar")
                        .HasColumnType("integer")
                        .HasColumnName("one_star");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("RecomputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recomputed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ThreeStar")
                        .HasColumnType("integer")
                        .HasColumnName("three_star");

                    b.Property<int>("TwoStar")
                        .HasColumnType("integer")
                        .HasColumnName("two_star");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_product_ratings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_ratings_tenant_id");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_ratings_product");

                    b.ToTable("product_ratings", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_product_ratings_average", "(average IS NULL AND count = 0) OR (average BETWEEN 1 AND 5 AND count > 0)");

                            t.HasCheckConstraint("ck_product_ratings_histogram", "one_star >= 0 AND two_star >= 0 AND three_star >= 0 AND four_star >= 0 AND five_star >= 0 AND one_star + two_star + three_star + four_star + five_star = count");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnswerCount")
                        .HasColumnType("integer")
                        .HasColumnName("answer_count");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("moderated_at");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("moderated_by");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderation_note");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("report_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_questions_tenant_id");

                    b.HasIndex("TenantId", "ProductId", "Status")
                        .HasDatabaseName("ix_questions_tenant_id_product_id_status");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_questions_tenant_id_status_created_at");

                    b.ToTable("questions", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_questions_status", "status IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer")
                        .HasColumnName("helpful_count");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified_purchase");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("moderated_at");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("moderated_by");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderation_note");

                    b.Property<int>("NotHelpfulCount")
                        .HasColumnType("integer")
                        .HasColumnName("not_helpful_count");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("report_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<DateTimeOffset?>("VendorRepliedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("vendor_replied_at");

                    b.Property<Guid?>("VendorRepliedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_replied_by");

                    b.Property<string>("VendorReply")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("vendor_reply");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reviews_tenant_id");

                    b.HasIndex("TenantId", "OrderLineId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_order_line");

                    b.HasIndex("TenantId", "CustomerId", "ProductId")
                        .HasDatabaseName("ix_reviews_tenant_id_customer_id_product_id");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_reviews_tenant_id_status_created_at");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_reviews_tenant_id_vendor_id_status");

                    b.HasIndex("TenantId", "ProductId", "Status", "PublishedAt")
                        .HasDatabaseName("ix_reviews_tenant_id_product_id_status_published_at");

                    b.ToTable("reviews", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_reviews_counts", "helpful_count >= 0 AND not_helpful_count >= 0 AND report_count >= 0");

                            t.HasCheckConstraint("ck_reviews_rating", "rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_reviews_status", "status IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.ReviewVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_review_votes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_review_votes_tenant_id");

                    b.HasIndex("ReviewId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_review_votes_voter");

                    b.ToTable("review_votes", "reviews");
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.StockSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("notified_at");

                    b.Property<decimal?>("NotifiedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("notified_price");

                    b.Property<decimal?>("PriceAtSubscription")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_at_subscription");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_subscriptions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_stock_subscriptions_expiring")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_subscriptions_tenant_id");

                    b.HasIndex("TenantId", "CustomerId", "Status")
                        .HasDatabaseName("ix_stock_subscriptions_tenant_id_customer_id_status");

                    b.HasIndex("TenantId", "VariantId", "Kind")
                        .HasDatabaseName("ix_stock_subscriptions_waiting")
                        .HasFilter("status = 'Active'");

                    b.ToTable("stock_subscriptions", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_stock_subscriptions_contact", "customer_id IS NOT NULL OR email IS NOT NULL");

                            t.HasCheckConstraint("ck_stock_subscriptions_kind", "kind IN ('BackInStock', 'PriceDrop')");

                            t.HasCheckConstraint("ck_stock_subscriptions_price", "target_price IS NULL OR target_price > 0");

                            t.HasCheckConstraint("ck_stock_subscriptions_status", "status IN ('Active', 'Notified', 'Cancelled', 'Expired')");

                            t.HasCheckConstraint("ck_stock_subscriptions_target", "kind = 'PriceDrop' OR (target_price IS NULL AND price_at_subscription IS NULL)");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.VendorRatingSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Average")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("average");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("RecomputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recomputed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_vendor_ratings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vendor_ratings_tenant_id");

                    b.HasIndex("TenantId", "VendorId")
                        .IsUnique()
                        .HasDatabaseName("ux_vendor_ratings_vendor");

                    b.ToTable("vendor_ratings", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_vendor_ratings_average", "(average IS NULL AND count = 0) OR (average BETWEEN 1 AND 5 AND count > 0)");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("share_token");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_wishlists");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlists_share_token")
                        .HasFilter("share_token IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_wishlists_tenant_id");

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlists_default")
                        .HasFilter("is_default");

                    b.HasIndex("TenantId", "CustomerId", "Name")
                        .HasDatabaseName("ix_wishlists_tenant_id_customer_id_name");

                    b.ToTable("wishlists", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_wishlists_item_count", "item_count >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("note");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_wishlist_items_tenant_id");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_wishlist_items_tenant_id_product_id");

                    b.HasIndex("WishlistId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_items_variant");

                    b.ToTable("wishlist_items", "reviews", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_items_priority", "priority >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Answer", b =>
                {
                    b.HasOne("KlaraHome.Modules.Reviews.Domain.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Review", b =>
                {
                    b.OwnsMany("KlaraHome.Modules.Reviews.Domain.ReviewImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("ReviewId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Caption");

                            b1.Property<Guid>("FileId");

                            b1.HasKey("ReviewId", "__synthesizedOrdinal");

                            b1.ToTable("reviews", "reviews");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId")
                                .HasConstraintName("fk_reviews_reviews_review_id");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.WishlistItem", b =>
                {
                    b.HasOne("KlaraHome.Modules.Reviews.Domain.Wishlist", null)
                        .WithMany("Items")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_items_wishlists_wishlist_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("KlaraHome.Modules.Reviews.Domain.Wishlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
