// <auto-generated />
using System;
using System.Collections.Generic;
using KlaraHome.Modules.Content.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlaraHome.Modules.Content.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260912163142_AddBannerMarquee")]
    partial class AddBannerMarquee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MessageId", "Handler")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("alt_text");

                    b.Property<int>("Audience")
                        .HasColumnType("integer")
                        .HasColumnName("audience");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CtaLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cta_label");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMarquee")
                        .HasColumnType("boolean")
                        .HasColumnName("is_marquee");

                    b.Property<string>("Link")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link");

                    b.Property<Guid?>("MediaFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_file_id");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<Guid?>("MobileMediaFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobile_media_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("placement");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_banners");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_banners_tenant_id");

                    b.HasIndex("TenantId", "Placement", "Priority")
                        .HasDatabaseName("ix_banners_tenant_id_placement_priority")
                        .HasFilter("is_active");

                    b.ToTable("banners", "content", t =>
                        {
                            t.HasCheckConstraint("ck_banners_audience", "audience BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_banners_content", "(placement = 'AnnouncementBar' AND message IS NOT NULL) OR (placement <> 'AnnouncementBar' AND media_file_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_banners_placement", "placement IN ('AnnouncementBar', 'HomeHero', 'HomeStrip', 'CategoryHeader', 'ListingSidebar', 'ProductStrip', 'CartStrip')");

                            t.HasCheckConstraint("ck_banners_window", "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<bool>("IsFromRule")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_rule");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_collection_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_collection_items_tenant_id");

                    b.HasIndex("CollectionId", "Position")
                        .HasDatabaseName("ix_collection_items_collection_id_position");

                    b.HasIndex("CollectionId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_collection_items_collection_id_product_id");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_collection_items_tenant_id_product_id");

                    b.ToTable("collection_items", "content", t =>
                        {
                            t.HasCheckConstraint("ck_collection_items_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("block_type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_page_blocks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_page_blocks_tenant_id");

                    b.HasIndex("PageId", "Position")
                        .HasDatabaseName("ix_page_blocks_page_id_position");

                    b.ToTable("page_blocks", "content", t =>
                        {
                            t.HasCheckConstraint("ck_page_blocks_position", "position >= 0");

                            t.HasCheckConstraint("ck_page_blocks_type", "block_type IN ('Hero', 'BannerGrid', 'ProductCarousel', 'CategoryTiles', 'RichText', 'Faq', 'Testimonial', 'CustomHtml')");

                            t.HasCheckConstraint("ck_page_blocks_window", "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ContentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset?>("ContentChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("content_changed_at");

                    b.Property<Guid?>("CoverImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_image_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pages_tenant_id");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_pages_due")
                        .HasFilter("status = 'Scheduled'");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_tenant_id_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_pages_single_published_home")
                        .HasFilter("type = 'Home' AND status = 'Published' AND deleted_at IS NULL");

                    b.HasIndex("TenantId", "Status", "Slug")
                        .HasDatabaseName("ix_pages_tenant_id_status_slug");

                    b.HasIndex("TenantId", "Type", "PublishedAt")
                        .HasDatabaseName("ix_pages_tenant_id_type_published_at");

                    b.ToTable("pages", "content", t =>
                        {
                            t.HasCheckConstraint("ck_pages_schedule", "(status = 'Scheduled' AND scheduled_at IS NOT NULL) OR (status <> 'Scheduled' AND scheduled_at IS NULL)");

                            t.HasCheckConstraint("ck_pages_status", "status IN ('Draft', 'InReview', 'Scheduled', 'Published', 'Unpublished', 'Archived')");

                            t.HasCheckConstraint("ck_pages_type", "type IN ('Home', 'Landing', 'Static', 'Legal', 'Blog')");

                            t.HasCheckConstraint("ck_pages_version", "version >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Placement")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("placement");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_menus_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_menus_tenant_id_code");

                    b.ToTable("menus", "content");
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Badge")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("badge");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<Guid?>("IconFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("icon_file_id");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("link_type");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<bool>("OpensInNewTab")
                        .HasColumnType("boolean")
                        .HasColumnName("opens_in_new_tab");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_menu_items_tenant_id");

                    b.HasIndex("MenuId", "ParentId", "Position")
                        .HasDatabaseName("ix_menu_items_menu_id_parent_id_position");

                    b.ToTable("menu_items", "content", t =>
                        {
                            t.HasCheckConstraint("ck_menu_items_depth", "depth >= 0 AND depth < 3");

                            t.HasCheckConstraint("ck_menu_items_link_target", "(link_type IN ('Page', 'Category', 'Collection') AND target_id IS NOT NULL) OR (link_type = 'Url' AND url IS NOT NULL) OR (link_type = 'None' AND target_id IS NULL AND url IS NULL)");

                            t.HasCheckConstraint("ck_menu_items_link_type", "link_type IN ('None', 'Page', 'Category', 'Collection', 'Url')");

                            t.HasCheckConstraint("ck_menu_items_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.PageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Blocks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blocks");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int?>("RestoredFrom")
                        .HasColumnType("integer")
                        .HasColumnName("restored_from");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_page_versions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_page_versions_tenant_id");

                    b.HasIndex("PageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_page_versions_page_id_version");

                    b.ToTable("page_versions", "content", t =>
                        {
                            t.HasCheckConstraint("ck_page_versions_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ProductCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ContentChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("content_changed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("HeroImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_image_file_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsListed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_listed");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RefreshedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refreshed_at");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_collections_tenant_id");

                    b.HasIndex("Kind", "RefreshedAt")
                        .HasDatabaseName("ix_collections_stale")
                        .HasFilter("type = 'Rule' AND deleted_at IS NULL");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_tenant_id_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("collections", "content", t =>
                        {
                            t.HasCheckConstraint("ck_collections_counts", "item_count >= 0");

                            t.HasCheckConstraint("ck_collections_type", "type IN ('Manual', 'Rule')");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.Redirect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FromPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("from_path");

                    b.Property<long>("HitCount")
                        .HasColumnType("bigint")
                        .HasColumnName("hit_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastHitAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_hit_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("to_path");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_redirects");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_redirects_tenant_id");

                    b.HasIndex("TenantId", "FromPath")
                        .IsUnique()
                        .HasDatabaseName("ix_redirects_tenant_id_from_path");

                    b.ToTable("redirects", "content", t =>
                        {
                            t.HasCheckConstraint("ck_redirects_hit_count", "hit_count >= 0");

                            t.HasCheckConstraint("ck_redirects_status_code", "status_code IN (301, 302, 410)");

                            t.HasCheckConstraint("ck_redirects_target", "(status_code = 410 AND to_path IS NULL) OR (status_code <> 410 AND to_path IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ContentBlock", b =>
                {
                    b.HasOne("KlaraHome.Modules.Content.Domain.ContentPage", null)
                        .WithMany("Blocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_blocks_pages_page_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ContentPage", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Content.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("ContentPageId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoFollow");

                            b1.Property<bool>("NoIndex");

                            b1.Property<string>("OgDescription");

                            b1.Property<Guid?>("OgImageFileId");

                            b1.Property<string>("OgTitle");

                            b1.Property<string>("OgType");

                            b1.Property<decimal?>("SitemapPriority");

                            b1.HasKey("ContentPageId")
                                .HasName("pk_pages");

                            b1.ToTable("pages", "content");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ContentPageId")
                                .HasConstraintName("fk_pages_pages_content_page_id");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.MenuItem", b =>
                {
                    b.HasOne("KlaraHome.Modules.Content.Domain.Menu", null)
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_menus_menu_id");
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.PageVersion", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Content.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("PageVersionId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoFollow");

                            b1.Property<bool>("NoIndex");

                            b1.Property<string>("OgDescription");

                            b1.Property<Guid?>("OgImageFileId");

                            b1.Property<string>("OgTitle");

                            b1.Property<string>("OgType");

                            b1.Property<decimal?>("SitemapPriority");

                            b1.HasKey("PageVersionId");

                            b1.ToTable("page_versions", "content");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PageVersionId")
                                .HasConstraintName("fk_page_versions_page_versions_id");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ProductCollection", b =>
                {
                    b.OwnsOne("KlaraHome.Modules.Content.Domain.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("ProductCollectionId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("MetaDescription");

                            b1.Property<string>("MetaKeywords");

                            b1.Property<string>("MetaTitle");

                            b1.Property<bool>("NoFollow");

                            b1.Property<bool>("NoIndex");

                            b1.Property<string>("OgDescription");

                            b1.Property<Guid?>("OgImageFileId");

                            b1.Property<string>("OgTitle");

                            b1.Property<string>("OgType");

                            b1.Property<decimal?>("SitemapPriority");

                            b1.HasKey("ProductCollectionId");

                            b1.ToTable("collections", "content");

                            b1
                                .ToJson("seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductCollectionId")
                                .HasConstraintName("fk_collections_collections_id");
                        });

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.ContentPage", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("KlaraHome.Modules.Content.Domain.Menu", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
